### ISSUE TITLE
Get this document moved into the KB ASAP and link back and forth between them.

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/SecDev-Tools#30]
https://github.com/techservicesillinois/SecDev-Tools/wiki/Example-Cybersecurity-Development-Standards

**Comment by edthedev** [comment]
Submitted document https://answers.uillinois.edu/kbAdmin/document.php?group_id=180&sta=4&id=106122 for review.

**Comment by edthedev** [comment]
I've fixed the link from the 'example logging' to point to the KB article, which will soon be updated with the example logging from this wiki.

**Comment by edthedev** [comment]
I've also submitted this article for activation.

**Comment by edthedev** [comment]
Hi Ed Delaport:

The following KB document has been activated [for University of Illinois Technology Services].

Document ID: 106122
Document title: Example Cybersecurity Development Standards.

Thank you for requesting activation of this document.

Ryan Sharpe
rtsharpe@illinois.edu

**Comment by mpitcel** [comment]
I am closing this as it is in "Done"
