### ISSUE TITLE
Prototype implementation of GitHub log collector for Splunk

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/SecDev-Tools#31]
See #26 for analysis.

**Comment by edthedev** [comment]
Planning to use LocalStack to develop and test this.

**Comment by ddriddle** [comment]
Request GitHub repo for this work: https://github.com/techservicesillinois/secdev-github-splunk-ingestion.

**Comment by edthedev** [comment]
I have pushed this back too many times for COVID; so I have asked SecEng to come to my rescue by helping us setup the more trivial connector we discussed previously – the one that I was previously the one objecting to using. 

https://servicedesk.cites.illinois.edu/jira/browse/SECINTR-487
